name: bmi_calculator_flutter
description: A simple BMI Calculator app built with Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    uses-material-design: true
  assets:
    - assets/images/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
